// surface/surface_test.go
// Copyright(c) vice contributors, licensed under the GNU Public License, Version 3.
// SPDX: GPL-3.0-only

package surface

import (
	"bytes"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/mmp/vice/math"
)

// testAptDat describes a small airport with an east-west runway 09/27
// and:
//   - a parallel taxiway A to the south, joined to the runway at each
//     end by stubs A1 (at 09) and A3 (at 27),
//   - taxiway B, which crosses the runway at its midpoint,
//   - a ramp node with a gate, connected to A at B,
//   - a ground vehicle route node right at the gate, which must be
//     dropped so that the gate isn't attached to it.
//
// The stub and crossing edges nearest the runway are in its active zone,
// so their outer nodes are hold-short points. Other airports precede and
// follow it to exercise the parser's airport selection.
//
//	               10 B1
//	                |
//	                9 HB2
//	09              |              27
//	 0 ============ 1 ============ 2
//	 |              |              |
//	 3 H0           8 HB1          7 H2
//	 |              |              |
//	 4 A0 -------- 5 A1n -------- 6 A2
//	                |
//	               11 G (gate)
const testAptDat = `I
1130 Generated by hand

1   100 0 0 KXXX Decoy Before
100 30.00 1 0 0.25 0 2 0 18 39.00000000 -100.00000000 0 0 2 0 0 0 36 38.98000000 -100.00000000 0 0 2 0 0 0
1201 39.00000000 -100.00000000 both 0 decoy

1   6000 1 0 KTST Test Field
1302 datum_lat 40.0
1302 datum_lon -99.985
100 45.72 1 0 0.25 0 2 0 09 40.00000000 -100.00000000 0 0 2 0 0 0 27 40.00000000 -99.97000000 30.48 0 2 0 0 0
14 39.99000000 -99.99000000 100 0 Tower
1300 39.98990000 -99.98500000 0.0 gate jets|turboprops Gate 1
1301 C airline aal,ual
1200
1201 39.98990000 -99.98500000 both 50 Fuel_stop
1201 40.00000000 -100.00000000 both 0 R0
1201 40.00000000 -99.98500000 both 1 R1
1201 40.00000000 -99.97000000 both 2 R2
1201 39.99800000 -100.00000000 both 3 H0
1201 39.99500000 -100.00000000 both 4 A0
1201 39.99500000 -99.98500000 both 5 A1n
1201 39.99500000 -99.97000000 both 6 A2
1201 39.99800000 -99.97000000 both 7 H2
1201 39.99800000 -99.98500000 both 8 HB1
1201 40.00200000 -99.98500000 both 9 HB2
1201 40.00500000 -99.98500000 both 10 B1
1201 39.99000000 -99.98500000 both 11 G
1202 0 1 twoway runway 09/27
1202 1 2 twoway runway 09/27
1202 0 3 twoway taxiway_E A1
1204 departure 09,27
1204 arrival 09,27
1202 3 4 twoway taxiway_E A1
1202 4 5 twoway taxiway_E A
1202 5 6 twoway taxiway_E A
1202 6 7 twoway taxiway_E A3
1202 7 2 twoway taxiway_E A3
1204 departure 09,27
1204 arrival 09,27
1202 5 8 twoway taxiway_E B
1202 8 1 twoway taxiway_E B
1204 departure 09,27
1204 ils 09
1202 1 9 twoway taxiway_E B
1204 departure 09,27
1202 9 10 twoway taxiway_E B
1202 11 5 twoway taxiway_E
1206 50 11 twoway Fuel

1   200 0 0 KYYY Decoy After
1201 41.00000000 -100.00000000 both 0 decoy
99
`

func loadTestAirport(t *testing.T) *Airport {
	t.Helper()
	ap, err := ParseAptDat(strings.NewReader(testAptDat), "KTST")
	if err != nil {
		t.Fatalf("ParseAptDat: %v", err)
	}
	return ap
}

func TestParseAptDat(t *testing.T) {
	ap := loadTestAirport(t)

	if ap.ElevationFt != 6000 {
		t.Errorf("elevation: got %v, want 6000", ap.ElevationFt)
	}
	if ap.Reference != (math.Point2LL{-99.985, 40}) {
		t.Errorf("reference: got %v", ap.Reference)
	}
	if ap.TowerLocation != (math.Point2LL{-99.99, 39.99}) {
		t.Errorf("tower location: got %v", ap.TowerLocation)
	}
	if len(ap.Nodes) != 12 || len(ap.Edges) != 13 {
		t.Fatalf("got %d nodes and %d edges, want 12 and 13", len(ap.Nodes), len(ap.Edges))
	}

	if len(ap.Runways) != 1 {
		t.Fatalf("got %d runways, want 1", len(ap.Runways))
	}
	rwy := ap.Runways[0]
	if rwy.Id() != "09/27" {
		t.Errorf("runway id: got %q", rwy.Id())
	}
	if math.Abs(rwy.WidthFt-150) > 0.1 {
		t.Errorf("runway width: got %v ft, want 150", rwy.WidthFt)
	}
	if math.Abs(rwy.Ends[1].DisplacedThresholdFt-100) > 0.1 {
		t.Errorf("27 displaced threshold: got %v ft, want 100", rwy.Ends[1].DisplacedThresholdFt)
	}

	e := ap.Edges[2] // 0-3 A1, in the active zone
	if e.Name != "A1" || e.WidthCode != "E" || e.Runway || len(e.Zones) != 2 {
		t.Errorf("edge 2: got %+v", e)
	}
	if got := e.ProtectedRunwayEnds(false); !slices.Equal(got, []string{"09", "27"}) {
		t.Errorf("edge 2 protected runway ends: got %v", got)
	}
	if !ap.Edges[0].Runway || ap.Edges[0].Name != "09/27" {
		t.Errorf("edge 0: got %+v", ap.Edges[0])
	}
	if ap.Edges[12].Name != "" {
		t.Errorf("unnamed edge: got name %q", ap.Edges[12].Name)
	}

	if len(ap.Gates) != 1 {
		t.Fatalf("got %d gates, want 1", len(ap.Gates))
	}
	g := ap.Gates[0]
	if g.Name != "Gate 1" || g.Kind != "gate" || g.SizeCode != "C" ||
		!slices.Equal(g.Types, []string{"jets", "turboprops"}) || !slices.Equal(g.Airlines, []string{"AAL", "UAL"}) {
		t.Errorf("gate: got %+v", g)
	}
}

func TestParseAptDatErrors(t *testing.T) {
	if _, err := ParseAptDat(strings.NewReader(testAptDat), "KZZZ"); err == nil {
		t.Errorf("expected error for missing airport")
	}
	if _, err := ParseAptDat(strings.NewReader(testAptDat), "KYYY"); err == nil {
		t.Errorf("expected error for airport without runways")
	}
	bad := strings.Replace(testAptDat, "1202 9 10 twoway", "1202 9 99 twoway", 1)
	if _, err := ParseAptDat(strings.NewReader(bad), "KTST"); err == nil {
		t.Errorf("expected error for edge with undefined node")
	}
}

func TestFindRoute(t *testing.T) {
	ap := loadTestAirport(t)

	tests := []struct {
		name           string
		req            RouteRequest
		wantNodes      []NodeID
		wantHoldShorts []HoldShort
		wantTaxiways   []string
	}{
		{
			name:           "gate to runway 09 via A",
			req:            RouteRequest{From: 11, To: []NodeID{0}, Via: []string{"A"}},
			wantNodes:      []NodeID{11, 5, 4, 3, 0},
			wantHoldShorts: []HoldShort{{Index: 3, RunwayEnds: []string{"09", "27"}}},
			wantTaxiways:   []string{"A", "A1"},
		},
		{
			name:           "gate to runway 27 via A",
			req:            RouteRequest{From: 11, To: []NodeID{2}, Via: []string{"a"}},
			wantNodes:      []NodeID{11, 5, 6, 7, 2},
			wantHoldShorts: []HoldShort{{Index: 3, RunwayEnds: []string{"09", "27"}}},
			wantTaxiways:   []string{"A", "A3"},
		},
		{
			// Crossing the runway on B gives a single hold short even though
			// it passes through two active-zone edges.
			name:           "cross the runway via B",
			req:            RouteRequest{From: 11, To: []NodeID{10}, Via: []string{"B"}},
			wantNodes:      []NodeID{11, 5, 8, 1, 9, 10},
			wantHoldShorts: []HoldShort{{Index: 2, RunwayEnds: []string{"09", "27"}}},
			wantTaxiways:   []string{"B"},
		},
		{
			name:           "runway edges are not used by default",
			req:            RouteRequest{From: 3, To: []NodeID{2}},
			wantNodes:      []NodeID{3, 4, 5, 6, 7, 2},
			wantHoldShorts: []HoldShort{{Index: 4, RunwayEnds: []string{"09", "27"}}},
		},
		{
			name:           "taxi down the runway when allowed",
			req:            RouteRequest{From: 3, To: []NodeID{2}, TaxiOnRunways: []string{"27"}},
			wantNodes:      []NodeID{3, 0, 1, 2},
			wantHoldShorts: []HoldShort{{Index: 0, RunwayEnds: []string{"09", "27"}}},
		},
		{
			name:           "runway named in via",
			req:            RouteRequest{From: 3, To: []NodeID{2}, Via: []string{"A1", "09"}},
			wantNodes:      []NodeID{3, 0, 1, 2},
			wantHoldShorts: []HoldShort{{Index: 0, RunwayEnds: []string{"09", "27"}}},
		},
		{
			// An arrival that exited at B is already on the runway, so
			// there's no hold short as it leaves.
			name:      "exit the runway to the gate",
			req:       RouteRequest{From: 1, To: []NodeID{11}, Via: []string{"B"}},
			wantNodes: []NodeID{1, 8, 5, 11},
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			r, err := ap.FindRoute(tc.req)
			if err != nil {
				t.Fatalf("FindRoute: %v", err)
			}
			if !slices.Equal(r.Nodes, tc.wantNodes) {
				t.Errorf("nodes: got %v, want %v", r.Nodes, tc.wantNodes)
			}
			if len(r.Edges) != len(r.Nodes)-1 {
				t.Errorf("got %d edges for %d nodes", len(r.Edges), len(r.Nodes))
			}
			if !slices.EqualFunc(r.HoldShorts, tc.wantHoldShorts, func(a, b HoldShort) bool {
				return a.Index == b.Index && slices.Equal(a.RunwayEnds, b.RunwayEnds)
			}) {
				t.Errorf("hold shorts: got %+v, want %+v", r.HoldShorts, tc.wantHoldShorts)
			}
			if tc.wantTaxiways != nil && !slices.Equal(r.Taxiways(ap), tc.wantTaxiways) {
				t.Errorf("taxiways: got %v, want %v", r.Taxiways(ap), tc.wantTaxiways)
			}
		})
	}
}

func TestFindRouteFailures(t *testing.T) {
	ap := loadTestAirport(t)

	if _, err := ap.FindRoute(RouteRequest{From: 11, To: []NodeID{0}, Via: []string{"Q"}}); err == nil {
		t.Errorf("expected error for nonexistent taxiway")
	}
	if _, err := ap.FindRoute(RouteRequest{From: 11, To: []NodeID{0}, SizeCode: "F"}); err == nil {
		t.Errorf("expected error for aircraft too large for the taxiways")
	}
	if _, err := ap.FindRoute(RouteRequest{From: 99, To: []NodeID{0}}); err == nil {
		t.Errorf("expected error for invalid origin")
	}
}

func TestHoldShortsILS(t *testing.T) {
	ap := loadTestAirport(t)

	r, err := ap.FindRoute(RouteRequest{From: 11, To: []NodeID{10}, Via: []string{"B"}})
	if err != nil {
		t.Fatalf("FindRoute: %v", err)
	}
	hs := ap.HoldShorts(r, true)
	if len(hs) != 1 || hs[0].Index != 2 || !slices.Equal(hs[0].RunwayEnds, []string{"09", "27"}) {
		t.Errorf("hold shorts with ILS: got %+v", hs)
	}
}

func TestRunwayConnections(t *testing.T) {
	ap := loadTestAirport(t)

	conns := ap.RunwayConnections("09")
	type conn struct {
		node    NodeID
		taxiway string
		right   bool
	}
	var got []conn
	for _, c := range conns {
		got = append(got, conn{c.Node, c.Taxiway, c.Right})
		if math.Abs(c.Angle-90) > 1 {
			t.Errorf("%s at node %d: angle %v, want 90", c.Taxiway, c.Node, c.Angle)
		}
	}
	// Heading east down 09, taxiways to the south are on the right.
	want := []conn{{0, "A1", true}, {1, "B", true}, {1, "B", false}, {2, "A3", true}}
	if !slices.Equal(got, want) {
		t.Errorf("connections: got %v, want %v", got, want)
	}
	if conns[0].Distance != 0 || math.Abs(conns[3].Distance-ap.Distance(ap.Nodes[0].Location, ap.Nodes[2].Location)) > 1e-4 {
		t.Errorf("unexpected connection distances %v and %v", conns[0].Distance, conns[3].Distance)
	}

	// From 27, everything is reversed.
	conns = ap.RunwayConnections("27")
	if conns[0].Node != 2 || conns[0].Right || conns[len(conns)-1].Node != 0 {
		t.Errorf("27 connections: got %+v", conns)
	}

	if n, ok := ap.DepartureEntry("09"); !ok || n != 0 {
		t.Errorf("09 departure entry: got %d, %v", n, ok)
	}
	if n, ok := ap.DepartureEntry("27"); !ok || n != 2 {
		t.Errorf("27 departure entry: got %d, %v", n, ok)
	}
	if _, ok := ap.DepartureEntry("18"); ok {
		t.Errorf("expected no departure entry for nonexistent runway")
	}
	if n, ok := ap.GateNode(ap.Gates[0]); !ok || n != 11 {
		t.Errorf("gate node: got %d, %v", n, ok)
	}
}

func TestRenameRunwayEnd(t *testing.T) {
	ap := loadTestAirport(t)
	ap.RenameRunwayEnd("09", "10")

	if ap.Runways[0].Id() != "10/27" {
		t.Errorf("runway: got %s", ap.Runways[0].Id())
	}
	if ap.Edges[0].Name != "10/27" {
		t.Errorf("runway edge: got %s", ap.Edges[0].Name)
	}
	if got := ap.Edges[2].ProtectedRunwayEnds(false); !slices.Equal(got, []string{"10", "27"}) {
		t.Errorf("zone: got %v", got)
	}
	if _, ok := ap.DepartureEntry("10"); !ok {
		t.Errorf("no departure entry for renamed runway end")
	}
}

func TestLocalCoordinates(t *testing.T) {
	ap := loadTestAirport(t)

	p := math.Point2LL{-99.97, 40.0}
	l := ap.Local(p)
	// float32 longitudes near 100 degrees are only good to ~7.6e-6
	// degrees, or ~3.5e-4nm.
	if math.Abs(l[1]) > 1e-5 || math.Abs(l[0]-0.015*ap.NMPerLongitude()) > 1e-3 {
		t.Errorf("Local: got %v", l)
	}
	if q := ap.FromLocal(l); math.Abs(q[0]-p[0]) > 1e-5 || math.Abs(q[1]-p[1]) > 1e-5 {
		t.Errorf("FromLocal(Local(p)): got %v, want %v", q, p)
	}

	// The 09/27 runway is 150' wide, running east-west.
	outline := ap.RunwayOutline(ap.Runways[0])
	width := ap.Distance(outline[0], outline[3]) * math.NauticalMilesToFeet
	if math.Abs(width-150) > 1 {
		t.Errorf("runway outline width: got %v ft, want 150", width)
	}
}

func TestEncodeDecode(t *testing.T) {
	ap := loadTestAirport(t)
	outline := ap.RunwayOutline(ap.Runways[0])
	ap.Polygons = []Polygon{{Kind: PolygonRunway, Rings: [][]math.Point2LL{outline[:]}}}

	var buf bytes.Buffer
	if err := ap.Encode(&buf); err != nil {
		t.Fatalf("Encode: %v", err)
	}
	ap2, err := Decode(&buf)
	if err != nil {
		t.Fatalf("Decode: %v", err)
	}
	if len(ap2.Nodes) != len(ap.Nodes) || len(ap2.Edges) != len(ap.Edges) || len(ap2.Polygons) != 1 ||
		ap2.Gates[0].Name != ap.Gates[0].Name || ap2.Edges[2].Zones[0].Kind != ZoneDeparture {
		t.Errorf("round trip mismatch: %+v", ap2)
	}
	// Derived state must be rebuilt so that routing works.
	if _, err := ap2.FindRoute(RouteRequest{From: 11, To: []NodeID{0}, Via: []string{"A"}}); err != nil {
		t.Errorf("FindRoute after decode: %v", err)
	}
}

func TestReadCRCASDEX(t *testing.T) {
	dir := t.TempDir()
	write := func(path, contents string) {
		path = filepath.Join(dir, path)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("ARTCCs/ZXX.json", `{
	  "facility": {"id": "ZXX", "childFacilities": [
	    {"id": "T01", "childFacilities": [
	      {"id": "TST", "asdexConfiguration": {"videoMapId": "MAP1", "towerLocation": {"lat": 39.99, "lon": -99.99}}}
	    ]}
	  ]},
	  "videoMaps": [{"id": "MAP1", "name": "TST SAID"}]
	}`)
	write("VideoMaps/ZXX/MAP1.geojson", `{"type": "FeatureCollection", "features": [
	  {"type": "Feature", "properties": {"asdex": "runway"},
	   "geometry": {"type": "MultiPolygon", "coordinates": [[[[-100, 40], [-99.97, 40], [-99.97, 40.001], [-100, 40.001], [-100, 40]]]]}},
	  {"type": "Feature", "properties": {"asdex": "apron"},
	   "geometry": {"type": "Polygon", "coordinates": [
	     [[-99.99, 39.99], [-99.98, 39.99], [-99.98, 39.995], [-99.99, 39.995], [-99.99, 39.99]],
	     [[-99.988, 39.991], [-99.987, 39.991], [-99.987, 39.992], [-99.988, 39.991]]]}}
	]}`)

	a, err := ReadCRCASDEX(dir, "ZXX", "TST")
	if err != nil {
		t.Fatalf("ReadCRCASDEX: %v", err)
	}
	if a.MapName != "TST SAID" || a.TowerLocation != (math.Point2LL{-99.99, 39.99}) {
		t.Errorf("got map %q tower %v", a.MapName, a.TowerLocation)
	}
	if len(a.Polygons) != 2 {
		t.Fatalf("got %d polygons, want 2", len(a.Polygons))
	}
	if a.Polygons[0].Kind != PolygonRunway || len(a.Polygons[0].Rings) != 1 || len(a.Polygons[0].Rings[0]) != 4 {
		t.Errorf("runway polygon: got %+v", a.Polygons[0])
	}
	if a.Polygons[1].Kind != PolygonApron || len(a.Polygons[1].Rings) != 2 || len(a.Polygons[1].Rings[1]) != 3 {
		t.Errorf("apron polygon: got %+v", a.Polygons[1])
	}

	if _, err := ReadCRCASDEX(dir, "ZXX", "T01"); err == nil {
		t.Errorf("expected error for facility without ASDE-X")
	}
	if _, err := ReadCRCASDEX(dir, "ZXX", "NOPE"); err == nil {
		t.Errorf("expected error for missing facility")
	}
}

// TestKCOS checks the generated surface data for the pilot airport: every
// runway end can be reached from every gate, and each route ends by
// holding short of the departure runway.
func TestKCOS(t *testing.T) {
	ap, err := LoadAirport("KCOS")
	if err != nil {
		t.Fatalf("LoadAirport: %v", err)
	}
	if len(ap.Polygons) == 0 || len(ap.Gates) == 0 {
		t.Errorf("got %d polygons and %d gates", len(ap.Polygons), len(ap.Gates))
	}

	for _, end := range []string{"17L", "35R", "17R", "35L", "13", "31"} {
		entry, ok := ap.DepartureEntry(end)
		if !ok {
			t.Errorf("%s: no departure entry", end)
			continue
		}
		for _, g := range ap.Gates {
			from, ok := ap.GateNode(g)
			if !ok {
				t.Fatalf("%s: no gate node", g.Name)
			}
			r, err := ap.FindRoute(RouteRequest{From: from, To: []NodeID{entry}})
			if err != nil {
				t.Errorf("%s to %s: %v", g.Name, end, err)
				continue
			}
			if len(r.HoldShorts) == 0 || !slices.Contains(r.HoldShorts[len(r.HoldShorts)-1].RunwayEnds, end) {
				t.Errorf("%s to %s: route doesn't hold short of the runway: %+v", g.Name, end, r.HoldShorts)
			}
		}
	}
}
