// surface/surface.go
// Copyright(c) vice contributors, licensed under the GNU Public License, Version 3.
// SPDX: GPL-3.0-only

// Package surface models an airport's movement area for tower control:
// the runways, the taxi routing network (including the runway "active
// zones" that define where aircraft must hold short), gates, and the
// filled polygons that an ASDE-X display draws.
//
// Airports are stored as zstd-compressed JSON in resources/surface and are
// generated by cmd/surfacegen from X-Plane Scenery Gateway apt.dat files
// (taxi network, runways, gates) and, when available, CRC ASDE-X video
// maps (polygons).
package surface

import (
	"encoding/json"
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/mmp/vice/math"
	"github.com/mmp/vice/util"

	"github.com/klauspost/compress/zstd"
)

// PolygonKind classifies the surface polygons drawn by ASDE-X; the
// values match the "asdex" property used in CRC ASDE-X video maps.
type PolygonKind string

const (
	PolygonApron     PolygonKind = "apron"
	PolygonTaxiway   PolygonKind = "taxiway"
	PolygonRunway    PolygonKind = "runway"
	PolygonStructure PolygonKind = "structure"
)

// DrawOrder returns the order in which polygons of the given kind should
// be drawn so that runways are on top of taxiways, which are on top of
// aprons. Structures are drawn last.
func (k PolygonKind) DrawOrder() int {
	switch k {
	case PolygonApron:
		return 0
	case PolygonTaxiway:
		return 1
	case PolygonRunway:
		return 2
	case PolygonStructure:
		return 3
	default:
		return 4
	}
}

type Polygon struct {
	Kind PolygonKind `json:"kind"`
	// Rings[0] is the outer boundary; any further rings are holes.
	Rings [][]math.Point2LL `json:"rings"`
}

type RunwayEnd struct {
	Id                   string        `json:"id"`
	Threshold            math.Point2LL `json:"threshold"`
	DisplacedThresholdFt float32       `json:"displaced_threshold_ft,omitempty"`
}

// Runway is a physical runway; Ends[0] and Ends[1] are opposite ends
// (e.g., "17L" and "35R").
type Runway struct {
	Ends    [2]RunwayEnd `json:"ends"`
	WidthFt float32      `json:"width_ft"`
}

// Id returns the runway's designator in the form "17L/35R".
func (r Runway) Id() string {
	return r.Ends[0].Id + "/" + r.Ends[1].Id
}

// HasEnd reports whether id names one of the runway's ends.
func (r Runway) HasEnd(id string) bool {
	return r.Ends[0].Id == id || r.Ends[1].Id == id
}

type NodeID int32

type Node struct {
	Location math.Point2LL `json:"location"`
	Name     string        `json:"name,omitempty"`
}

type ZoneKind string

const (
	ZoneDeparture ZoneKind = "departure"
	ZoneArrival   ZoneKind = "arrival"
	// ZoneILS marks ILS critical areas; aircraft only hold short of them
	// when ILS critical areas are protected (low IMC).
	ZoneILS ZoneKind = "ils"
)

// ActiveZone records that an edge lies within the protected area of one
// or more runways, so an aircraft must be cleared before entering it.
type ActiveZone struct {
	Kind ZoneKind `json:"kind"`
	// RunwayEnds lists runway end identifiers, e.g. ["17R", "35L"].
	RunwayEnds []string `json:"runway_ends"`
}

// Edge is a segment of the taxi routing network between two nodes.
type Edge struct {
	A NodeID `json:"a"`
	B NodeID `json:"b"`
	// Name is the taxiway designator (e.g. "C3") or, for runway edges,
	// the runway designator (e.g. "17R/35L").
	Name   string `json:"name,omitempty"`
	Runway bool   `json:"runway,omitempty"`
	// OneWay edges may only be traversed from A to B.
	OneWay bool `json:"one_way,omitempty"`
	// WidthCode is the ICAO aircraft size code (A-F) of the largest
	// aircraft that may use the edge; empty if unrestricted.
	WidthCode string       `json:"width_code,omitempty"`
	Zones     []ActiveZone `json:"zones,omitempty"`
}

// Other returns the node at the opposite end of the edge from n.
func (e Edge) Other(n NodeID) NodeID {
	if e.A == n {
		return e.B
	}
	return e.A
}

// ProtectedRunwayEnds returns the runway ends whose protected area the
// edge is in: those of its departure and arrival active zones (and ILS
// zones if includeILS is set) as well as the runway itself for runway
// edges.
func (e Edge) ProtectedRunwayEnds(includeILS bool) []string {
	var ends []string
	for _, z := range e.Zones {
		if z.Kind == ZoneILS && !includeILS {
			continue
		}
		for _, r := range z.RunwayEnds {
			if !slices.Contains(ends, r) {
				ends = append(ends, r)
			}
		}
	}
	if e.Runway {
		for r := range strings.SplitSeq(e.Name, "/") {
			if r != "" && !slices.Contains(ends, r) {
				ends = append(ends, r)
			}
		}
	}
	slices.Sort(ends)
	return ends
}

type Gate struct {
	Name     string           `json:"name"`
	Location math.Point2LL    `json:"location"`
	Heading  math.TrueHeading `json:"heading"`
	// Kind is "gate", "hangar", "tie_down" or "misc".
	Kind string `json:"kind,omitempty"`
	// Types lists the classes of aircraft that may use the gate: some of
	// "heavy", "jets", "turboprops", "props", "helos", "fighters".
	Types []string `json:"types,omitempty"`
	// SizeCode is the ICAO aircraft size code (A-F) of the largest
	// aircraft the gate can take; empty if unspecified.
	SizeCode string `json:"size_code,omitempty"`
	// Airlines lists ICAO airline codes that use the gate; empty means any.
	Airlines []string `json:"airlines,omitempty"`
}

type Airport struct {
	ICAO          string        `json:"icao"`
	ElevationFt   float32       `json:"elevation_ft"`
	Reference     math.Point2LL `json:"reference"`
	TowerLocation math.Point2LL `json:"tower_location"`
	Runways       []Runway      `json:"runways"`
	Nodes         []Node        `json:"nodes"`
	Edges         []Edge        `json:"edges"`
	Gates         []Gate        `json:"gates,omitempty"`
	Polygons      []Polygon     `json:"polygons,omitempty"`
	// Sources records where the data came from, for attribution.
	Sources []string `json:"sources,omitempty"`

	nmPerLongitude float32
	adjacency      [][]int // node -> indices of edges incident to it
}

// Finalize checks the airport's internal consistency and initializes the
// derived data structures that the routing and geometry methods use. It
// must be called after an Airport is unmarshaled or built by hand.
func (ap *Airport) Finalize() error {
	if ap.ICAO == "" {
		return fmt.Errorf("airport ICAO code not set")
	}
	if ap.Reference.IsZero() {
		if len(ap.Nodes) == 0 {
			return fmt.Errorf("%s: no reference point and no nodes", ap.ICAO)
		}
		ap.Reference = ap.Nodes[0].Location
	}
	ap.nmPerLongitude = math.NMPerLongitudeAt(ap.Reference)

	ap.adjacency = make([][]int, len(ap.Nodes))
	for i, e := range ap.Edges {
		for _, n := range []NodeID{e.A, e.B} {
			if n < 0 || int(n) >= len(ap.Nodes) {
				return fmt.Errorf("%s: edge %d (%s) references invalid node %d", ap.ICAO, i, e.Name, n)
			}
		}
		if e.A == e.B {
			return fmt.Errorf("%s: edge %d (%s) is a loop on node %d", ap.ICAO, i, e.Name, e.A)
		}
		ap.adjacency[e.A] = append(ap.adjacency[e.A], i)
		ap.adjacency[e.B] = append(ap.adjacency[e.B], i)
	}
	for _, rwy := range ap.Runways {
		if rwy.Ends[0].Id == "" || rwy.Ends[1].Id == "" {
			return fmt.Errorf("%s: runway with missing end identifier", ap.ICAO)
		}
	}
	return nil
}

// NMPerLongitude returns the number of nautical miles per degree of
// longitude at the airport.
func (ap *Airport) NMPerLongitude() float32 {
	return ap.nmPerLongitude
}

// Local returns the offset of p from the airport reference point in
// nautical miles (x east, y north). Computing the offset before scaling
// keeps full float32 precision for points near the airport.
func (ap *Airport) Local(p math.Point2LL) [2]float32 {
	d := math.Sub2LL(p, ap.Reference)
	return [2]float32{d[0] * ap.nmPerLongitude, d[1] * 60}
}

// FromLocal is the inverse of Local.
func (ap *Airport) FromLocal(p [2]float32) math.Point2LL {
	return math.Add2LL(ap.Reference, math.Point2LL{p[0] / ap.nmPerLongitude, p[1] / 60})
}

// Distance returns the distance in nautical miles between two points near
// the airport.
func (ap *Airport) Distance(a, b math.Point2LL) float32 {
	return math.Length2f(math.Sub2f(ap.Local(a), ap.Local(b)))
}

// EdgeLength returns the length of the given edge in nautical miles.
func (ap *Airport) EdgeLength(edge int) float32 {
	e := ap.Edges[edge]
	return ap.Distance(ap.Nodes[e.A].Location, ap.Nodes[e.B].Location)
}

// EdgesAt returns the indices of the edges incident to the given node.
func (ap *Airport) EdgesAt(n NodeID) []int {
	return ap.adjacency[n]
}

// NearestNode returns the node closest to p for which accept returns true
// (or the closest overall if accept is nil), along with its distance from
// p in nautical miles. It returns -1 if no node is acceptable.
func (ap *Airport) NearestNode(p math.Point2LL, accept func(NodeID) bool) (NodeID, float32) {
	best, bestDist := NodeID(-1), float32(0)
	for i, n := range ap.Nodes {
		id := NodeID(i)
		if accept != nil && !accept(id) {
			continue
		}
		if d := ap.Distance(p, n.Location); best == -1 || d < bestDist {
			best, bestDist = id, d
		}
	}
	return best, bestDist
}

// LookupRunway returns the runway with an end with the given identifier
// (e.g., "35L"), along with the index of that end in Runway.Ends.
func (ap *Airport) LookupRunway(end string) (Runway, int, bool) {
	for _, rwy := range ap.Runways {
		for i, e := range rwy.Ends {
			if e.Id == end {
				return rwy, i, true
			}
		}
	}
	return Runway{}, 0, false
}

// RunwayOutline returns the four corners of the runway's paved rectangle
// (threshold to threshold, ignoring displaced thresholds and blast pads),
// for use when no surface polygons are available.
func (ap *Airport) RunwayOutline(rwy Runway) [4]math.Point2LL {
	p0, p1 := ap.Local(rwy.Ends[0].Threshold), ap.Local(rwy.Ends[1].Threshold)
	dir := math.Normalize2f(math.Sub2f(p1, p0))
	halfWidth := rwy.WidthFt / 2 * math.FeetToNauticalMiles
	perp := math.Scale2f([2]float32{-dir[1], dir[0]}, halfWidth)
	return [4]math.Point2LL{
		ap.FromLocal(math.Add2f(p0, perp)),
		ap.FromLocal(math.Add2f(p1, perp)),
		ap.FromLocal(math.Sub2f(p1, perp)),
		ap.FromLocal(math.Sub2f(p0, perp)),
	}
}

///////////////////////////////////////////////////////////////////////////
// Serialization

// ResourcePath returns the path within the resources directory of the
// surface data for the given airport.
func ResourcePath(icao string) string {
	return "surface/" + icao + ".json.zst"
}

// HasAirport reports whether surface data is available for the airport.
func HasAirport(icao string) bool {
	return util.ResourceExists(ResourcePath(icao))
}

// LoadAirport loads the surface data for the given airport from the
// resources directory.
func LoadAirport(icao string) (*Airport, error) {
	if !HasAirport(icao) {
		return nil, fmt.Errorf("%s: no surface data available", icao)
	}
	// LoadResource takes care of decompression.
	r := util.LoadResource(ResourcePath(icao))
	defer r.Close()
	return decodeJSON(r)
}

// Decode reads an airport in the format written by Encode.
func Decode(r io.Reader) (*Airport, error) {
	zr, err := zstd.NewReader(r)
	if err != nil {
		return nil, err
	}
	defer zr.Close()
	return decodeJSON(zr)
}

func decodeJSON(r io.Reader) (*Airport, error) {
	var ap Airport
	if err := json.NewDecoder(r).Decode(&ap); err != nil {
		return nil, err
	}
	if err := ap.Finalize(); err != nil {
		return nil, err
	}
	return &ap, nil
}

// Encode writes the airport as zstd-compressed JSON.
func (ap *Airport) Encode(w io.Writer) error {
	zw, err := zstd.NewWriter(w, zstd.WithEncoderLevel(zstd.SpeedBestCompression))
	if err != nil {
		return err
	}
	enc := json.NewEncoder(zw)
	if err := enc.Encode(ap); err != nil {
		zw.Close()
		return err
	}
	return zw.Close()
}
